version: '3'

services:
  storybook:
    container_name: storybook
    build: .
    ports:
      - "8080:8080"    #for vue
      - "6006:6006"    #for storybook
    volumes:
      - .:/src
    tty: true